[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements-minimal.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python main.py"
