[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python main.py"
