services:
  - type: web
    name: rag-chatbot-backend
    env: python
    rootDirectory: .
    buildCommand: |
      pip install --no-cache-dir --upgrade pip setuptools wheel
      pip install --no-cache-dir -r backend/requirements-minimal.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
